### PR TITLE
V1.4 release

### LINKED ISSUE #22: timestamps
As a user, I would   like to be clearly shown which timestamp is used (right, left, middle).

### PR DESCRIPTION
**Pull request by christian-rli**
Closes #22 #32 #54 #57

### CODE REVIEW

**Comment by Ludee** [comment]
Perfect, all issues considered. Ready to merge from my side.
We decided to gice a new version number, since there are multiple version of v1.4 now.
So this one would be **v1.4.1** or **v1.5**!?

**Comment by Bachibouzouk** [comment]
> So this one would be **v1.4.1** or **v1.5**!?

@Ludee Side note on the release format: I would stick with "three digit" release number format, i.e. v1.5.0 in case it should be v1.5. This [reference guide](https://semver.org/) for semantic versioning could also help answer your question.

**Comment by christian-rli** [comment]
I would go with either using 1.4.0 or based on the recommendations in the reference guide linked by @Bachibouzouk 2.0.0. It's tricky. My reason for both in both options is, that there was no real 1.4.0 before. 

I realize that there are strings compatible with an almost complete version 1.4.0. But 1.4.0 was never declared complete. There would be a weird gap of versions, because what is 1.4.0 then? Why isn't there a function to convert from it? It's been codenamed 1.4 all along would just need to be declared "done" now.

2.0.0, could make sense, because if we create a new version number, this would reflect not being downwards-compatible to 1.3.0.

**Comment by Ludee** [comment]
I would favour:
`"metadataVersion": "OEP-1.4.0"`

All unofficial versions were labelled "1.4" and can be updated easily.

**Comment by christian-rli** [comment]
> I would favour:
> `"metadataVersion": "OEP-1.4.0"`
> 
> All unofficial versions were labelled "1.4" 

Clever! Let's just stick with `"metadataVersion": "OEP-1.4.0"` then.

**Comment by Ludee** [comment]
Final changes are added to all three files!

**Pull request merged**
